services:
  chatwoot:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/store
    env_file:
      - .env
    ports:
      - 3001:3000

  db:
    image: pgvector/pgvector:pg16
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    image: valkey/valkey:latest
    volumes:
      - ./redis:/data
    env_file:
      - .env