services:
  kavita:
    image: jvmilazz0/kavita:latest # Using the stable branch from the official dockerhub repo.
    container_name: kavita
    volumes:
      - ./manga:/manga
      - ./comics:/comics
      - ./boock:/books
      - ./config:/kavita/config # /kavita/config must not be changed
    environment:
      - TZ=Your/Timezone
    ports:
      - "5000:5000"
    restart: unless-stopped
