
[pacman]
installed = [
	"flatpak",
	"openssh",
	"podman",
	"tmux",
	"yazi",
	"ffmpeg",
	"7zip",
	"jq",
	"poppler",
	"zoxide",
	"resvg",
	"imagemagick"
]

openssh = """
sudo systemctl enable sshd
sudo systemctl start sshd
"""

[flatpak]
installed = [
	"barrier",
	"podman-desktop",
]

[pwsh]
install = "alternative install - from wiki"

[docker-compose]
install = "legacy install"
enable = "sudo chmod +x docker-compose"

[repositories]
personal = [
	"dotfiles",
	"a-cli"
	"personal-docs"
]

[rust]
install = "follow instructions"
cargo = [
	"bob-nvim",
	"dua-cli",
	"nu",
	"zellij",
	"xcp"
]
