services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - PYTHONPATH=/workspace
    networks:
      - dev-network

  cache:
    image: redis:latest
    networks:
      - dev-network
    volumes:
      - ../.cache:/data

networks:
  dev-network:
    driver: bridge
