pending = [
	"brew",
	"docker",
	"nix",
	"git",
	"neovim",
	"go",
	"pwsh",
	"starship",
	"zellij",
	"fzf",
	"ripgrep",
	"fd",
	"yazi",
	"bat",
	"dua",
]

[pacman]
packages = [
	"base-devel",
	"git",
	"openssh",
	"ttf-nerd-fonts-symbols-mono",
	"wezterm",
	"chezmoi",
]

[[pacman.openssh]]
config = """
sudo systemctl enable sshd
sudo systemctl start sshd
"""
status = "sudo systemctl status sshd"

[nix]

[yay]
install = """
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
"""

[cargo]
install = """
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
"""
packages = [
	"cargo",
	"rust",
	"bob-nvim",
	"nu",
]

[[cargo.nu]]
attempt = 4
fail = """
error: failed to build archive at `/tmp/cargo-installI9HJbg/release/deps/libtabled-5221fef07b75705f.rlib`: Disk quota exceeded (os error 122)

error: could not compile `tabled` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.107.0`, intermediate artifacts can be found at `/tmp/cargo-installI9HJbg`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
"""
datails = """
2. agregar la variable de entorno CARGO_TARGET_DIR, pero persiste el error
- Resultado: el error persiste
3. purge /tmp
- cambio el error, pero no, es decir avanzo mas pero persiste el error
4. borre mas cosas, purge /tmp, y cambie el valor de entorno CARGO_TARGET_DIR
- Success!
"""

