services:
  nginx:
    image: nginx:alpine
    env_file:
      - ./nginx.env
    ports:
      - "${PORT:-3001}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    restart: always
